Ps 29 tests/0
PoSanie-Team/posanie pull request #32
Opened 2023-03-29 13:50 UTC by EinTheFrog

2023-04-04 18:26 UTC, vldF requested changes

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/ExampleInstrumentedTest.kt
>  }
Давай сделаем автоматическое раставление новых пустых строк в конце файла (а то и GH красным светит, и так просто принято, можешь погуглить и почитать подробнее)
![image](https://user-images.githubusercontent.com/21011268/229876796-1b7b9714-ed5c-4b81-974c-ab6413bcac2b.png)
(ну и добавить можно везде в рамках этого ПР)

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/FakeGroupsUseCase.kt
> +    override suspend fun getPickedGroup(): Result<Group> {
В котлине (по крайней мере, в обычных unit-тестах) есть практика использования библиотек вроде mockito+powermock. Они позволяют не городить кучу моков (то, что ты написал это как раз фейк или мок, одно и то же, по сути). Посмотри, возможно, тебе понравится

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/FakeGroupsUseCase.kt
> +    override suspend fun getPickedGroup(): Result<Group> {
Как раз уйдут классы, в которых все функции не заимплеменчены. Там есть нюансы с моком object'ов и еще некоторые, но тут будет норм

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/SchedulerTest.kt
> +class SchedulerTest {
Для юниттестов есть хороший паттерн arrange/act/assert. Он помогает поддерживать тесты (не надо думать, а вызов функции это подготовка теста или это сам тест)
https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/SchedulerTest.kt
> +class SchedulerTest {
Еще, бегло посмотрев, тут у тебя тут почти всё обычные unit-тесты. Для них есть отдельная папочка `test`. в которой даже уже есть пример. Лучше их перенести туда

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/SchedulerTest.kt
> +        assert(workingWeekDay == WeekDay.SATURDAY)
Ты используешь неправильные ассерты (они котлиновские, из стандартной библиотеки). Это плохо потому что:
1. Они недостаточно информативные (несмотря на то, что ты туда можешь запихать любую ерунду, все ошибки будут одинаковыми)
2. Семантика нарушена: ассерты из JUnit показывают не только то, что ты хочешь, чтобы условие было истинным, а более точечно показывают детали этого условия (например, переменная null, коллекции равны между собой и т.д)

Используй ассерты из JUnit. Для этого нужно подключить зависимость `testImplementation "junit:junit-api:4.13.2"`

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/SchedulerTest.kt
> +package dev.timatifey.posanie
У тебя есть неиспользуемые импорты -- убери их и поставь галочку, чтобы они при коммите чистились сами

2023-04-04 18:26 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/FakeGroupsUseCase.kt
> +    override suspend fun getPickedGroup(): Result<Group> {
Ну и было бы неплохо разделить файлики с моками и сами тесты

2023-04-05 15:49 UTC, EinTheFrog commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/SchedulerTest.kt
> +class SchedulerTest {
Спасибо, почитал. А в чем я откланяюсь от arrange/act/assert? Пустые строки плохо расставлены? Или мне нужно комменты написать чтобы было понятнее?

2023-04-07 08:28 UTC, vldF commented on posanie/app/src/androidTest/java/dev/timatifey/posanie/SchedulerTest.kt
> +class SchedulerTest {
1. Да, лучше комменты
2. У тебя ассерты в перемешку со всем остальным. По этому паттерну (который, очевидно, не постулат) всё должно идти блоками, без вставки ассертов в часть инициализации, например

2023-04-18 14:25 UTC, vldF requested changes

2023-04-18 14:25 UTC, vldF commented on posanie/app/src/test/java/dev/timatifey/posanie/ExampleUnitTest.kt
>  package dev.timatifey.posanie
Этот файл так сильно нужен?

2023-04-18 15:15 UTC, vldF approved these changes

2023-04-18 15:16 UTC, merged