Ps 37 extended lesson card/0
PoSanie-Team/posanie pull request #33
Opened 2023-04-25 13:53 UTC by EinTheFrog

2023-04-30 11:55 UTC, timatifey requested changes
Небольшие замечания и вопросы

2023-04-30 11:55 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +            if (it) {
DRY, тут отличается только `painterResource`, так его и выбирай в зависимости от `state`. Потом, убрать `it` - нормальное название аргумента лямбды

2023-04-30 11:55 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> -    fetchLessons: () -> Unit
Чтобы такого не было, добавили необязательную запятую в Kotlin

2023-04-30 11:55 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +            val isExpanded = lesson == expandedLesson
Нет смысла выделять это в отдельную переменную с именем `isExpanded` и потом передавать `isExpanded = isExpanded`, также и с `lesson`

2023-04-30 11:55 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerViewModel.kt
> +            if (lesson != viewModelState.value.expandedLesson) return@launch
ИМХО, инлайнить `if` - нехорошо

2023-04-30 11:55 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                    text = "Some additional information about this lesson bla bla bla bla bla.",
wtf

2023-04-30 11:55 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                IconButton(
Кажется я что-то упустил, а зачем тогда нужно было писать `TwoStateIcon()`?

2023-04-30 14:58 UTC, EinTheFrog commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +            val isExpanded = lesson == expandedLesson
Если я не буду выделять в отдельную переменную то я 2 раза буду использовать lessons[index]. Разе не лучше для читаемости в таких случаях выносить элемент массива в отдельную переменную?

2023-04-30 14:58 UTC, EinTheFrog commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                IconButton(
В процессе разработки я понял что `TwoStateicon()` не нужен и удалил его

2023-04-30 15:00 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                IconButton(
А в коммите остался... не надо так

2023-04-30 15:01 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +            val isExpanded = lesson == expandedLesson
Да, с lesson[index] норм

2023-04-30 15:29 UTC, EinTheFrog commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                IconButton(
А как надо? Засквошить?

2023-04-30 15:30 UTC, EinTheFrog commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                    text = "Some additional information about this lesson bla bla bla bla bla.",
Старый коммит

2023-04-30 15:37 UTC, timatifey commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +                IconButton(
Вообще да, но не критично

2023-05-02 13:07 UTC, EinTheFrog commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> +            if (it) {
В новых коммитах этого кода нет

2023-05-02 13:07 UTC, EinTheFrog commented on posanie/app/src/main/java/dev/timatifey/posanie/ui/scheduler/SchedulerScreen.kt
> -    fetchLessons: () -> Unit
Учту в будущем

2023-05-02 13:53 UTC, timatifey approved these changes

2023-05-02 13:54 UTC, merged